// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8mrxlzvrz22cgE5310dXLmtStslMAIDU',
    appId: '1:985930394568:web:957a860781b19c1128aefd',
    messagingSenderId: '985930394568',
    projectId: 'rosewater-cafe-app',
    authDomain: 'rosewater-cafe-app.firebaseapp.com',
    storageBucket: 'rosewater-cafe-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPFbLWIOU1kmmh85imKY-eIgnPGHyfqN0',
    appId: '1:985930394568:android:f0160cecd933641b28aefd',
    messagingSenderId: '985930394568',
    projectId: 'rosewater-cafe-app',
    storageBucket: 'rosewater-cafe-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBEcVdTMYd2cK0C7J7YQEu0AQlI9lM9qI',
    appId: '1:985930394568:ios:8d9ada8e5339622428aefd',
    messagingSenderId: '985930394568',
    projectId: 'rosewater-cafe-app',
    storageBucket: 'rosewater-cafe-app.firebasestorage.app',
    iosBundleId: 'com.example.rosewaterCafeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBEcVdTMYd2cK0C7J7YQEu0AQlI9lM9qI',
    appId: '1:985930394568:ios:8d9ada8e5339622428aefd',
    messagingSenderId: '985930394568',
    projectId: 'rosewater-cafe-app',
    storageBucket: 'rosewater-cafe-app.firebasestorage.app',
    iosBundleId: 'com.example.rosewaterCafeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8mrxlzvrz22cgE5310dXLmtStslMAIDU',
    appId: '1:985930394568:web:6c5ee8759d7869a128aefd',
    messagingSenderId: '985930394568',
    projectId: 'rosewater-cafe-app',
    authDomain: 'rosewater-cafe-app.firebaseapp.com',
    storageBucket: 'rosewater-cafe-app.firebasestorage.app',
  );
}
